on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

name: catalog

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container: rocker/geospatial:latest
    steps:
      - run: git config --system --add safe.directory '*'

      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
           set-safe-directory: '*'

      - name: install deps
        shell: Rscript {0}
        run: remotes::install_deps(".", dep=TRUE)

      - name: Render
        shell: Rscript {0}
        run: source("stac/update_stac.R")

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add stac/* .
          git commit -a -m "update catalog" || echo "nothing to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}

